// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDR9-xLs9VTo831_7sF3IwrliOPaDcXx5M',
    appId: '1:1062636932778:android:876e24f0f147caa12a0ad3',
    messagingSenderId: '1062636932778',
    projectId: 'test-firebase-fa771',
    storageBucket: 'test-firebase-fa771.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRzyBOGCpsG0GlmknaK6y65kunNBcChIY',
    appId: '1:1062636932778:web:32558f937c2aa0642a0ad3',
    messagingSenderId: '1062636932778',
    projectId: 'test-firebase-fa771',
    authDomain: 'test-firebase-fa771.firebaseapp.com',
    storageBucket: 'test-firebase-fa771.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKCjOrrzWtMcRS5HRuCQDTIyBRDGeGwiQ',
    appId: '1:1062636932778:ios:37b53186f370f0272a0ad3',
    messagingSenderId: '1062636932778',
    projectId: 'test-firebase-fa771',
    storageBucket: 'test-firebase-fa771.appspot.com',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKCjOrrzWtMcRS5HRuCQDTIyBRDGeGwiQ',
    appId: '1:1062636932778:ios:37b53186f370f0272a0ad3',
    messagingSenderId: '1062636932778',
    projectId: 'test-firebase-fa771',
    storageBucket: 'test-firebase-fa771.appspot.com',
    iosBundleId: 'com.example.testFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRzyBOGCpsG0GlmknaK6y65kunNBcChIY',
    appId: '1:1062636932778:web:2c6be444cf3fb34b2a0ad3',
    messagingSenderId: '1062636932778',
    projectId: 'test-firebase-fa771',
    authDomain: 'test-firebase-fa771.firebaseapp.com',
    storageBucket: 'test-firebase-fa771.appspot.com',
  );

}